version: '3'
services:
  mysql:
    platform: linux/x86_64
    container_name: mysql-app
    restart:  unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_api
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    image: mysql:8.0.32
    ports:
      - '33063:3306'
    volumes:
      - './app_data:/var/lib/mysql'
    command: mysqld --default-authentication-plugin=mysql_native_password
    networks:
      - net_app

networks:
  net_app:
    driver: bridge

volumes:
  app_data:
