version: '3'
services:
  app:
    container_name: app-php
    build: .
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/config/supervisord.conf:/etc/supervisor/supervisord.conf
    #      - ./docker/supervisor:/etc/supervisor
    networks:
      - net_app

  nginx:
    container_name: nginx-app
    image: nginx:1.21-alpine
    restart: unless-stopped
    ports:
      - ${PORT}:80
      #- 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    networks:
      - net_app

  elasticsearch:
    container_name: es-container
    image: elasticsearch:8.9.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - net_app
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: kibana:8.9.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - net_app
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  net_app:
    driver: bridge
