version: '3'
services:
  app:
    container_name: app-php
    build: .
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/config/supervisord.conf:/etc/supervisor/supervisord.conf
    #      - ./docker/supervisor:/etc/supervisor
    networks:
      - net_travel

  nginx:
    container_name: nginx-travel
    image: nginx:1.21-alpine
    restart: unless-stopped
    ports:
      - ${PORT}:80
      #- 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    networks:
      - net_travel

networks:
  net_travel:
    driver: bridge
